[package]
name = "utils"
version = "0.1.0"
authors = ["C.Solovev <constantine.solovev@gmail.com>"]
edition = "2018"

[dependencies]

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
